# Generated by Django 5.0.1 on 2024-02-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('whatsapp', models.TextField()),
                ('instagram', models.TextField()),
            ],
        ),
    ]
