# Generated by Django 5.0.2 on 2024-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs')),
                ('Date', models.DateField()),
                ('User', models.CharField(max_length=50)),
                ('Phara', models.TextField()),
            ],
        ),
    ]
