# Generated by Django 5.0.2 on 2024-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=99)),
                ('twitter', models.CharField(max_length=99)),
                ('whatsapp', models.CharField(max_length=99)),
                ('instagram', models.CharField(max_length=99)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='whatsapp',
        ),
    ]
