# Generated by Django 5.0.2 on 2024-02-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_media_teachers_facebook_teachers_instagram_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
